--liquibase formatted sql

--changeset rangan10:004-seed-kshema-aml-questionnaire
-- =====================================================================
-- AML Module Schema - 004
-- Seed data for tenant KSHEMA: "AML Risk Assessment Questionnaire"
--
-- NOTE on question types: the schema's question_type column is validated
-- against com.insurance.aml.enums.QuestionType, which only defines
-- TEXT, NUMBER, DATE, BOOLEAN, SINGLE_CHOICE, MULTI_CHOICE - there is no
-- DROPDOWN or YES_NO value. Inserting those literal strings would make the
-- app fail to deserialize the row (@Enumerated(EnumType.STRING) throws on
-- an unknown constant). This script therefore maps:
--   DROPDOWN -> SINGLE_CHOICE
--   YES_NO   -> BOOLEAN
-- All 30 requested questions are still present; only the stored type code
-- differs from the prompt's label.
--
-- NOTE on IDs: rather than hardcoding numeric primary keys (which could
-- collide with rows already generated by 003 or by the running app), every
-- insert below resolves foreign keys via natural/unique keys (tenant_code,
-- question_code, questionnaire_code + version). This keeps the script safe
-- to run regardless of what IDs already exist in the database.
--
-- NOTE on conditional_rule: QuestionnaireService stores this column as the
-- JSON serialization of ConditionalRuleDto {dependsOnQuestionCode, operator,
-- expectedValue}, compared case-insensitively against the free-text answer
-- of the question it depends on. BOOLEAN answers are expected as the
-- literal text "true"/"false".
-- =====================================================================

-- ==================== 3. AML_QUESTION (tenant-specific, owned by KSHEMA) ====================
INSERT INTO aml_question (
    question_code,
    question_text,
    question_type,
    question_scope
)
SELECT
    v.question_code,
    v.question_text,
    v.question_type,
    'TENANT_SPECIFIC'
FROM (
     VALUES
        ('EMPLOYMENT_TYPE',               'What is your employment type?',                                        'SINGLE_CHOICE'),
        ('COUNTRY_OF_RESIDENCE',          'What is your country of residence?',                                   'TEXT'),
        ('NRI_FLAG',                      'Are you a Non-Resident Indian (NRI)?',                                 'BOOLEAN'),
        ('PEP_FLAG',                      'Are you a Politically Exposed Person (PEP)?',                          'BOOLEAN'),
        ('RELATED_TO_PEP',                'Are you related to a Politically Exposed Person (PEP)?',              'BOOLEAN'),
        ('NGO_TRUST_AFFILIATION',         'Do you have any NGO or Trust affiliation?',                            'BOOLEAN'),
        ('ANNUAL_INCOME',                 'What is your annual income?',                                          'NUMBER'),
        ('SOURCE_OF_INCOME',              'What is your primary source of income?',                               'SINGLE_CHOICE'),
        ('CURRENT_ADDRESS',               'What is your current address?',                                        'TEXT'),
        ('PERMANENT_ADDRESS',             'What is your permanent address?',                                      'TEXT'),
        ('PAN_NUMBER',                    'What is your PAN number?',                                             'TEXT'),
        ('MOBILE_NUMBER',                 'What is your mobile number?',                                          'TEXT'),
        ('EMAIL_ADDRESS',                 'What is your email address?',                                          'TEXT'),
        ('CKYC_AVAILABLE',                'Is your CKYC record available?',                                       'BOOLEAN'),
        ('CKYC_KIN_NUMBER',               'What is your CKYC KIN number?',                                        'TEXT'),
        ('SUM_INSURED',                   'What is the sum insured for this policy?',                             'NUMBER'),
        ('PREMIUM_AMOUNT',                'What is the premium amount for this policy?',                          'NUMBER'),
        ('PAYMENT_MODE',                  'What is the mode of premium payment?',                                 'SINGLE_CHOICE'),
        ('PREMIUM_PAYER_TYPE',            'Who is paying the premium for this policy?',                           'SINGLE_CHOICE'),
        ('PAYER_NAME',                    'What is the payer''s name?',                                           'TEXT'),
        ('PAYER_PAN',                     'What is the payer''s PAN number?',                                     'TEXT'),
        ('RELATIONSHIP_TO_INSURED',       'What is the payer''s relationship to the insured?',                    'TEXT'),
        ('HYPOTHECATION_STATUS',          'What is the hypothecation status of the insured asset?',               'SINGLE_CHOICE'),
        ('NOMINEE_NAME',                  'What is the nominee''s name?',                                         'TEXT'),
        ('NOMINEE_RELATIONSHIP',          'What is the nominee''s relationship to the insured?',                  'TEXT'),
        ('ASSIGNEE_EXISTS',               'Does this policy have an assignee?',                                   'BOOLEAN'),
        ('BENEFICIAL_OWNER_FLAG',         'Is there a beneficial owner other than the insured/proposer?',         'BOOLEAN'),
        ('ULTIMATE_BENEFICIAL_OWNER_NAME','What is the name of the Ultimate Beneficial Owner (UBO)?',            'TEXT'),
        ('FOREIGN_SOURCE_OF_FUNDS',       'Is the source of funds for this policy from a foreign country?',       'BOOLEAN'),
        ('FOREIGN_COUNTRY',               'Which foreign country is the source of funds from?',                   'TEXT')
) AS v(question_code, question_text, question_type)
WHERE NOT EXISTS (
    SELECT 1
    FROM aml_question q
    WHERE q.question_code = v.question_code
);

-- ==================== 4. AML_QUESTION_OPTION ====================
INSERT INTO aml_question_option (
    question_id,
    option_code,
    option_label,
    display_order
)
SELECT
    q.question_id,
    v.option_code,
    v.option_label,
    v.display_order
FROM aml_question q,
(
    VALUES
        ('GOVERNMENT_EMPLOYEE', 'Government Employee', 1),
        ('SALARIED_EMPLOYEE',   'Salaried Employee',   2),
        ('SELF_EMPLOYED',       'Self Employed',       3),
        ('BUSINESS_OWNER',      'Business Owner',      4),
        ('FARMER',              'Farmer',              5),
        ('NGO',                 'NGO',                 6),
        ('TRUST',               'Trust',               7),
        ('OTHER',               'Other',               8)
) AS v(option_code, option_label, display_order)
WHERE q.question_code = 'EMPLOYMENT_TYPE'
  AND NOT EXISTS (
      SELECT 1
      FROM aml_question_option qo
      WHERE qo.question_id = q.question_id
        AND qo.option_code = v.option_code
  );


-- Source Of Income
INSERT INTO aml_question_option (
    question_id,
    option_code,
    option_label,
    display_order
)
SELECT
    q.question_id,
    v.option_code,
    v.option_label,
    v.display_order
FROM aml_question q,
(
    VALUES
        ('SALARY',         'Salary',         1),
        ('BUSINESS',       'Business',       2),
        ('AGRICULTURE',    'Agriculture',    3),
        ('RENTAL_INCOME',  'Rental Income',  4),
        ('PENSION',        'Pension',        5),
        ('INVESTMENTS',    'Investments',    6),
        ('INHERITANCE',    'Inheritance',    7),
        ('OTHER',          'Other',          8)
) AS v(option_code, option_label, display_order)
WHERE q.question_code = 'SOURCE_OF_INCOME'
  AND NOT EXISTS (
      SELECT 1
      FROM aml_question_option qo
      WHERE qo.question_id = q.question_id
        AND qo.option_code = v.option_code
  );


-- Payment Mode
INSERT INTO aml_question_option (
    question_id,
    option_code,
    option_label,
    display_order
)
SELECT
    q.question_id,
    v.option_code,
    v.option_label,
    v.display_order
FROM aml_question q,
(
    VALUES
        ('UPI',          'UPI',          1),
        ('NET_BANKING',  'Net Banking',  2),
        ('DEBIT_CARD',   'Debit Card',   3),
        ('CREDIT_CARD',  'Credit Card',  4),
        ('CASH',         'Cash',         5),
        ('DEMAND_DRAFT', 'Demand Draft', 6),
        ('NEFT',         'NEFT',         7),
        ('RTGS',         'RTGS',         8)
) AS v(option_code, option_label, display_order)
WHERE q.question_code = 'PAYMENT_MODE'
  AND NOT EXISTS (
      SELECT 1
      FROM aml_question_option qo
      WHERE qo.question_id = q.question_id
        AND qo.option_code = v.option_code
  );

-- Premium Payer Type
INSERT INTO aml_question_option (
    question_id,
    option_code,
    option_label,
    display_order
)
SELECT
    q.question_id,
    v.option_code,
    v.option_label,
    v.display_order
FROM aml_question q,
(
    VALUES
        ('PROPOSER', 'Proposer', 1),
        ('INSURED',  'Insured',  2),
        ('NOMINEE',  'Nominee',  3),
        ('OTHER',    'Other',    4)
) AS v(option_code, option_label, display_order)
WHERE q.question_code = 'PREMIUM_PAYER_TYPE'
  AND NOT EXISTS (
      SELECT 1
      FROM aml_question_option qo
      WHERE qo.question_id = q.question_id
        AND qo.option_code = v.option_code
  );


-- Hypothecation Status
INSERT INTO aml_question_option (
    question_id,
    option_code,
    option_label,
    display_order
)
SELECT
    q.question_id,
    v.option_code,
    v.option_label,
    v.display_order
FROM aml_question q,
(
    VALUES
        ('HYPOTHECATED',     'Hypothecated',     1),
        ('NON_HYPOTHECATED', 'Non Hypothecated', 2)
) AS v(option_code, option_label, display_order)
WHERE q.question_code = 'HYPOTHECATION_STATUS'
  AND NOT EXISTS (
      SELECT 1
      FROM aml_question_option qo
      WHERE qo.question_id = q.question_id
        AND qo.option_code = v.option_code
  );

-- ==================== 5. AML_TENANT_QUESTIONNAIRE (attaches questions to the questionnaire) ====================
-- Required by the schema: aml_question rows alone are not "in" a
-- questionnaire until mapped here, with mandatory/display_order/
-- conditional_rule carried per this tenant's configuration.

JOIN aml_question_tenant aqt
    ON aqt.question_id = q.question_id
   AND aqt.tenant_id = t.tenant_id
   AND aqt.version_no = 1
   AND aqt.active = TRUE

WHERE t.tenant_code = 'KSHEMA'
  AND NOT EXISTS (
        SELECT 1
        FROM aml_tenant_questionnaire existing
        WHERE existing.questionnaire_id = qn.questionnaire_id
          AND existing.question_id = q.question_id
  );
