----liquibase formatted sql
--
----changeset rangan10:005-questionnaire-tenant-many-to-many
---- =====================================================================
---- AML Module Schema - 005
---- Turns the tenant <-> questionnaire relationship into many-to-many: a
---- questionnaire becomes a shared, tenant-agnostic template. Which tenants
---- have adopted a given questionnaire is now tracked in the new
---- aml_questionnaire_tenant join table, instead of aml_questionnaire owning
---- a single tenant_id.
---- =====================================================================
--
---- ==================== Tenant <-> Questionnaire join table ====================
--
--CREATE TABLE aml_questionnaire_tenant (
--    questionnaire_tenant_id    BIGSERIAL PRIMARY KEY,
--    questionnaire_id           BIGINT NOT NULL REFERENCES aml_questionnaire(questionnaire_id),
--    tenant_id                  BIGINT NOT NULL REFERENCES tenant(tenant_id),
--    active                     BOOLEAN NOT NULL DEFAULT TRUE,
--    created_at                 TIMESTAMP NOT NULL DEFAULT now(),
--    updated_at                 TIMESTAMP NOT NULL DEFAULT now()
--);
--
--CREATE INDEX idx_questionnaire_tenant_questionnaire ON aml_questionnaire_tenant(questionnaire_id);
--CREATE INDEX idx_questionnaire_tenant_tenant ON aml_questionnaire_tenant(tenant_id);
--CREATE UNIQUE INDEX uq_questionnaire_tenant ON aml_questionnaire_tenant(questionnaire_id, tenant_id);
--
---- Backfill: every existing questionnaire's owning tenant becomes its first
---- (and, so far, only) adopter.
--INSERT INTO aml_questionnaire_tenant (questionnaire_id, tenant_id)
--SELECT questionnaire_id, tenant_id FROM aml_questionnaire;
--
---- ==================== Drop single-tenant ownership from aml_questionnaire ====================
--
--DROP INDEX IF EXISTS uq_questionnaire_tenant_code_version;
--
--ALTER TABLE aml_questionnaire DROP COLUMN tenant_id;
--
---- questionnaire_code + version now identifies a shared template globally,
---- not scoped to one tenant.
--CREATE UNIQUE INDEX uq_questionnaire_code_version ON aml_questionnaire(questionnaire_code, version);
--
---- ==================== Allow independent per-tenant question config ====================
---- Previously (questionnaire_id, question_id) was unique regardless of
---- tenant, which only worked because a questionnaire belonged to exactly one
---- tenant. Now that many tenants can share a questionnaire, each tenant needs
---- to be able to configure the same question independently.
--
--DROP INDEX IF EXISTS uq_tenant_questionnaire_question;
--
--CREATE UNIQUE INDEX uq_tenant_questionnaire_question ON aml_tenant_questionnaire(tenant_id, questionnaire_id, question_id);
